(ns bijector.words
  (:use bijector.core)
  (:import bijector.core.EnumerationDataType))

(def words
  {:interjection
     ["aye" "no" "well" "yeah" "yes"],
   :infinitive-marker
     ["to"],
   :pron
     ["anybody" "anyone" "anything" "everybody" "everyone" "everything" "he"
      "her" "herself" "him" "himself" "his" "i" "it" "itself" "me" "myself"
      "no-one" "nobody" "none" "nothing" "one" "other" "ourselves" "plenty"
      "she" "somebody" "someone" "something" "them" "themselves" "there" "they"
      "us" "we" "who" "whom" "you" "yourself"],
   :adj
     ["able" "academic" "active" "actual" "additional" "afraid" "alone"
      "alternative" "ancient" "annual" "apparent" "appropriate" "attractive"
      "available" "average" "aware" "bad" "basic" "beautiful" "big" "black"
      "bloody" "blue" "brief" "bright" "broad" "busy" "capable" "careful"
      "central" "certain" "cheap" "chief" "civil" "clean" "clear" "close"
      "cold" "commercial" "common" "complete" "complex" "concerned"
      "conservative" "considerable" "constant" "corporate" "correct" "criminal"
      "critical" "cultural" "current" "dangerous" "dark" "dead" "deep"
      "democratic" "detailed" "different" "difficult" "direct" "domestic"
      "double" "dry" "due" "early" "easy" "economic" "educational" "effective"
      "elderly" "empty" "entire" "environmental" "equal" "essential"
      "excellent" "existing" "expensive" "external" "extra" "fair" "familiar"
      "famous" "far" "fast" "female" "final" "financial" "fine" "first"
      "following" "foreign" "formal" "free" "fresh" "front" "full" "funny"
      "future" "general" "good" "great" "green" "grey" "growing" "happy" "hard"
      "heavy" "high" "historical" "hot" "huge" "human" "immediate" "important"
      "impossible" "increased" "independent" "individual" "industrial"
      "initial" "interested" "interesting" "internal" "international" "joint"
      "key" "labour" "large" "last" "late" "leading" "left" "legal" "liberal"
      "light" "likely" "limited" "little" "living" "local" "long" "lovely"
      "low" "main" "major" "male" "married" "medical" "mental" "military"
      "modern" "narrow" "national" "natural" "necessary" "new" "nice" "normal"
      "northern" "nuclear" "obvious" "odd" "official" "old" "only" "open"
      "ordinary" "original" "other" "overall" "particular" "past" "perfect"
      "permanent" "personal" "physical" "political" "poor" "popular" "positive"
      "possible" "potential" "powerful" "practical" "present" "previous"
      "primary" "prime" "private" "professional" "proper" "public" "quick"
      "quiet" "rare" "ready" "real" "reasonable" "recent" "red" "regional"
      "regular" "relative" "relevant" "religious" "responsible" "rich" "right"
      "royal" "rural" "safe" "scientific" "secondary" "senior" "separate"
      "serious" "severe" "sexual" "short" "significant" "similar" "simple"
      "single" "slow" "small" "social" "soft" "sorry" "southern" "special"
      "specific" "standard" "strange" "strong" "substantial" "successful"
      "sufficient" "suitable" "sure" "tall" "technical" "terrible" "thin"
      "tiny" "top" "total" "traditional" "true" "typical" "unable" "united"
      "unlikely" "upper" "urban" "used" "useful" "usual" "various" "vast"
      "very" "vital" "warm" "weak" "western" "white" "whole" "wide" "wild"
      "wonderful" "working" "wrong" "young"],
   :conj
     ["after" "although" "and" "as" "because" "before" "but" "cos" "except" "for"
      "if" "nor" "once" "or" "provided" "since" "so" "than" "that" "though"
      "unless" "until" "when" "where" "whereas" "whether" "while" "whilst"],
   :prep
     ["about" "above" "across" "after" "against" "along" "among" "amongst"
      "around" "as" "at" "before" "behind" "below" "beneath" "beside" "between"
      "beyond" "by" "despite" "down" "during" "for" "from" "in" "including"
      "inside" "into" "like" "near" "of" "off" "on" "onto" "outside" "over"
      "past" "per" "plus" "round" "since" "through" "throughout" "to" "towards"
      "under" "until" "up" "upon" "via" "with" "within" "without" "worth"],
   :modal
     ["can" "could" "may" "may" "might" "must" "ought" "shall" "should" "used"
      "will" "would"],
   :n
     ["ability" "absence" "access" "accident" "account" "achievement" "acid"
      "act" "action" "activity" "addition" "address" "administration" "adult"
      "advance" "advantage" "advice" "affair" "afternoon" "age" "agency"
      "agent" "agreement" "aid" "aim" "air" "aircraft" "alternative" "amount"
      "analysis" "animal" "answer" "appeal" "appearance" "application"
      "appointment" "approach" "area" "argument" "arm" "army" "arrangement"
      "art" "article" "artist" "aspect" "assembly" "assessment" "asset"
      "association" "assumption" "atmosphere" "attack" "attempt" "attention"
      "attitude" "audience" "author" "authority" "award" "baby" "back"
      "background" "bag" "balance" "ball" "band" "bank" "bar" "base" "basis"
      "battle" "bed" "bedroom" "beginning" "behaviour" "belief" "benefit"
      "bill" "bird" "birth" "bit" "block" "blood" "board" "boat" "body" "bone"
      "book" "border" "bottle" "bottom" "box" "boy" "brain" "branch" "breath"
      "bridge" "brother" "budget" "building" "bus" "business" "cabinet" "call"
      "campaign" "candidate" "capacity" "capital" "car" "card" "care" "career"
      "case" "cash" "cat" "category" "cause" "cell" "centre" "century" "chain"
      "chair" "chairman" "challenge" "chance" "change" "channel" "chapter"
      "character" "characteristic" "charge" "chemical" "child" "choice"
      "church" "circle" "circumstance" "citizen" "city" "claim" "class"
      "client" "clothes" "club" "coal" "code" "coffee" "colleague" "collection"
      "college" "colour" "combination" "comment" "commission" "commitment"
      "committee" "communication" "community" "company" "comparison"
      "competition" "component" "computer" "concentration" "concept" "concern"
      "conclusion" "condition" "conference" "confidence" "conflict" "congress"
      "connection" "consequence" "consideration" "construction" "consumer"
      "contact" "content" "context" "contract" "contrast" "contribution"
      "control" "convention" "conversation" "copy" "corner" "cost" "council"
      "country" "county" "couple" "course" "court" "cover" "creation" "credit"
      "crime" "crisis" "criterion" "criticism" "crowd" "culture" "cup"
      "curriculum" "customer" "cut" "damage" "danger" "data" "date" "daughter"
      "day" "deal" "death" "debate" "debt" "decade" "decision" "defence"
      "defendant" "definition" "degree" "demand" "department" "deputy"
      "description" "design" "desire" "desk" "detail" "development" "device"
      "difference" "difficulty" "dinner" "direction" "director" "discipline"
      "discussion" "disease" "display" "distance" "distinction" "distribution"
      "district" "division" "doctor" "document" "dog" "door" "doubt" "drawing"
      "dream" "dress" "drink" "drive" "driver" "drug" "duty" "ear" "earth"
      "east" "economy" "edge" "editor" "education" "effect" "effort" "egg"
      "election" "element" "emphasis" "employee" "employer" "employment" "end"
      "enemy" "energy" "engine" "engineering" "enterprise" "entry"
      "environment" "equipment" "error" "establishment" "estate" "evening"
      "event" "evidence" "examination" "example" "exchange" "executive"
      "exercise" "exhibition" "existence" "expectation" "expenditure" "expense"
      "experience" "experiment" "expert" "explanation" "expression" "extent"
      "eye" "face" "facility" "fact" "factor" "factory" "failure" "faith"
      "fall" "family" "farm" "farmer" "fashion" "father" "favour" "fear"
      "feature" "fee" "feeling" "few" "field" "figure" "file" "film" "finance"
      "finding" "finger" "fire" "firm" "fish" "flat" "flight" "floor" "flow"
      "flower" "food" "foot" "football" "force" "forest" "form" "foundation"
      "freedom" "friend" "front" "fruit" "fuel" "function" "fund" "future"
      "game" "garden" "gas" "gate" "general" "generation" "gentleman" "girl"
      "glass" "goal" "god" "gold" "good" "government" "grant" "ground" "group"
      "growth" "guest" "guide" "gun" "hair" "half" "hall" "hand" "head"
      "health" "heart" "heat" "hell" "help" "hill" "history" "hole" "holiday"
      "home" "hope" "horse" "hospital" "hotel" "hour" "house" "household"
      "housing" "human" "husband" "idea" "image" "impact" "implication"
      "importance" "impression" "improvement" "incident" "income" "increase"
      "index" "individual" "industry" "influence" "information" "initiative"
      "injury" "instance" "institute" "institution" "instruction" "instrument"
      "insurance" "intention" "interest" "interpretation" "interview"
      "introduction" "investigation" "investment" "iron" "island" "issue"
      "item" "job" "journey" "judge" "justice" "key" "kid" "kind" "king"
      "kitchen" "knee" "knowledge" "labour" "lack" "lady" "land" "language"
      "law" "lawyer" "lead" "leader" "leadership" "leaf" "league" "leg"
      "legislation" "length" "letter" "level" "liability" "library" "life"
      "light" "limit" "line" "link" "lip" "list" "literature" "loan" "location"
      "look" "lord" "loss" "lot" "love" "lunch" "machine" "magazine" "majority"
      "male" "man" "management" "manager" "manner" "map" "mark" "market"
      "marriage" "mass" "master" "match" "material" "matter" "meal" "meaning"
      "means" "measure" "mechanism" "media" "meeting" "member" "membership"
      "memory" "message" "metal" "method" "middle" "mile" "milk" "mind" "mine"
      "minister" "ministry" "minute" "mistake" "model" "module" "moment"
      "money" "month" "morning" "mother" "motion" "motor" "mountain" "mouth"
      "move" "movement" "murder" "museum" "music" "name" "nation" "nature"
      "neck" "need" "negotiation" "neighbour" "network" "news" "newspaper"
      "night" "noise" "north" "nose" "note" "notice" "notion" "number" "nurse"
      "object" "objective" "observation" "occasion" "offence" "offer" "office"
      "officer" "official" "oil" "operation" "opinion" "opportunity"
      "opposition" "option" "order" "organisation" "organization" "origin"
      "other" "outcome" "output" "owner" "package" "page" "pain" "painting"
      "pair" "panel" "paper" "parent" "park" "parliament" "part" "partner"
      "party" "passage" "past" "path" "patient" "pattern" "pay" "payment"
      "peace" "pension" "people" "percent" "performance" "period" "person"
      "phase" "phone" "photograph" "picture" "piece" "place" "plan" "planning"
      "plant" "plastic" "plate" "play" "player" "pleasure" "pocket" "point"
      "police" "policy" "politics" "pool" "population" "position" "possibility"
      "post" "potential" "pound" "power" "practice" "presence" "present"
      "president" "press" "pressure" "price" "principle" "priority" "prison"
      "prisoner" "problem" "procedure" "process" "product" "production"
      "profit" "program" "programme" "progress" "project" "property"
      "proportion" "proposal" "prospect" "protection" "provision" "pub"
      "public" "publication" "pupil" "purpose" "quality" "quarter" "question"
      "race" "radio" "railway" "rain" "range" "rate" "reaction" "reader"
      "reading" "reality" "reason" "recognition" "record" "reduction"
      "reference" "reform" "region" "regulation" "relation" "relationship"
      "release" "relief" "religion" "report" "representation" "representative"
      "request" "requirement" "research" "resource" "respect" "response"
      "responsibility" "rest" "restaurant" "result" "return" "revenue" "review"
      "revolution" "right" "ring" "rise" "risk" "river" "road" "rock" "role"
      "roof" "room" "route" "row" "rule" "run" "safety" "sale" "sample" "scale"
      "scene" "scheme" "school" "science" "scientist" "screen" "sea" "search"
      "season" "seat" "second" "secretary" "section" "sector" "security"
      "selection" "sense" "sentence" "sequence" "series" "servant" "service"
      "session" "set" "settlement" "sex" "shape" "share" "sheet" "ship" "shoe"
      "shop" "shot" "shoulder" "show" "side" "sight" "sign" "signal"
      "significance" "silence" "sir" "sister" "site" "situation" "size" "skill"
      "skin" "sky" "smile" "society" "software" "soil" "soldier" "solicitor"
      "solution" "son" "song" "sort" "sound" "source" "south" "space" "speaker"
      "species" "speech" "speed" "spirit" "sport" "spot" "spring" "staff"
      "stage" "standard" "star" "start" "state" "statement" "station" "status"
      "step" "stock" "stone" "store" "story" "strategy" "street" "strength"
      "strike" "structure" "student" "studio" "study" "stuff" "style" "subject"
      "success" "suggestion" "sum" "summer" "sun" "supply" "support" "surface"
      "surprise" "survey" "system" "table" "talk" "tape" "target" "task" "tax"
      "tea" "teacher" "teaching" "team" "tear" "technique" "technology"
      "telephone" "television" "temperature" "term" "terms" "test" "text"
      "thanks" "theatre" "theme" "theory" "thing" "thought" "threat" "ticket"
      "time" "title" "tone" "tool" "tooth" "top" "total" "touch" "tour" "town"
      "track" "trade" "tradition" "traffic" "train" "training" "transfer"
      "transport" "treatment" "treaty" "tree" "trend" "trial" "trip" "troop"
      "trouble" "trust" "truth" "turn" "type" "understanding" "unemployment"
      "union" "unit" "university" "use" "user" "value" "variation" "variety"
      "vehicle" "version" "victim" "victory" "video" "view" "village"
      "violence" "vision" "visit" "visitor" "voice" "volume" "vote" "wage"
      "walk" "wall" "war" "water" "wave" "way" "weapon" "weather" "week"
      "weekend" "weight" "welfare" "west" "while" "whole" "wife" "will" "wind"
      "window" "wine" "wing" "winner" "winter" "woman" "wood" "word" "work"
      "worker" "works" "world" "writer" "writing" "yard" "year" "youth"],
   :det
     ["a" "all" "an" "another" "any" "both" "each" "either" "enough" "every"
      "few" "former" "half" "her" "his" "its" "latter" "less" "little" "many"
      "more" "most" "much" "my" "next" "no" "our" "own" "same" "several" "some"
      "such" "that" "the" "their" "these" "this" "those" "what" "whatever"
      "which" "whose" "your"],
   :adv
     ["about" "above" "absolutely" "actually" "afterwards" "again" "ago" "ahead"
      "all" "almost" "alone" "along" "already" "alright" "also" "always"
      "anyway" "apart" "apparently" "around" "as" "away" "back" "before"
      "below" "best" "better" "both" "carefully" "certainly" "clearly" "close"
      "closely" "completely" "currently" "deep" "directly" "down" "early"
      "easily" "effectively" "either" "else" "elsewhere" "enough" "entirely"
      "equally" "especially" "even" "eventually" "ever" "exactly" "extremely"
      "fairly" "far" "fast" "finally" "forward" "frequently" "fully" "further"
      "generally" "hard" "hardly" "hence" "here" "high" "highly" "home" "how"
      "however" "immediately" "in" "increasingly" "indeed" "inside" "instead"
      "just" "largely" "late" "later" "least" "less" "little" "long" "mainly"
      "maybe" "meanwhile" "merely" "more" "most" "much" "nearly" "necessarily"
      "neither" "never" "nevertheless" "next" "no" "normally" "not" "now"
      "obviously" "off" "often" "okay" "on" "once" "only" "otherwise" "out"
      "outside" "over" "particularly" "partly" "perhaps" "please" "possibly"
      "pretty" "previously" "probably" "properly" "quickly" "quite" "rapidly"
      "rather" "really" "recently" "relatively" "right" "round" "seriously"
      "simply" "slightly" "slowly" "so" "sometimes" "somewhat" "somewhere"
      "soon" "still" "straight" "strongly" "suddenly" "surely" "then" "there"
      "therefore" "though" "through" "thus" "to" "today" "together" "tomorrow"
      "tonight" "too" "totally" "twice" "under" "unfortunately" "up" "usually"
      "very" "well" "when" "where" "why" "widely" "yesterday" "yet"],
   :v
     ["accept" "accompany" "account" "achieve" "acquire" "act" "add" "address"
      "admit" "adopt" "advise" "affect" "afford" "agree" "aim" "allow"
      "announce" "answer" "appeal" "appear" "apply" "appoint" "approach"
      "approve" "argue" "arise" "arrange" "arrive" "ask" "assess" "associate"
      "assume" "attach" "attack" "attempt" "attend" "attract" "avoid" "award"
      "base" "be" "bear" "beat" "become" "begin" "believe" "belong" "bind"
      "blow" "break" "bring" "build" "burn" "buy" "call" "care" "carry" "catch"
      "cause" "change" "charge" "check" "choose" "claim" "clear" "climb"
      "close" "collect" "combine" "come" "comment" "commit" "compare"
      "complete" "concentrate" "concern" "conclude" "conduct" "confirm"
      "connect" "consider" "consist" "contact" "contain" "continue"
      "contribute" "control" "cost" "count" "cover" "create" "cross" "cry"
      "cut" "damage" "date" "deal" "decide" "declare" "define" "deliver"
      "demand" "demonstrate" "deny" "depend" "derive" "describe" "design"
      "destroy" "determine" "develop" "die" "direct" "disappear" "discover"
      "discuss" "display" "divide" "do" "draw" "dress" "drink" "drive" "drop"
      "earn" "eat" "emerge" "employ" "enable" "encourage" "end" "enjoy"
      "ensure" "enter" "entitle" "escape" "establish" "estimate" "examine"
      "exercise" "exist" "expect" "experience" "explain" "explore" "express"
      "extend" "face" "fail" "fall" "fear" "feel" "fight" "fill" "find"
      "finish" "fit" "fix" "fly" "focus" "follow" "force" "forget" "form"
      "gain" "gather" "generate" "get" "give" "go" "grant" "grow" "hand"
      "handle" "hang" "happen" "hate" "have" "head" "hear" "help" "hide" "hit"
      "hold" "hope" "hurt" "identify" "ignore" "illustrate" "imagine" "imply"
      "impose" "improve" "include" "increase" "indicate" "influence" "inform"
      "insist" "intend" "introduce" "investigate" "invite" "involve" "issue"
      "join" "judge" "jump" "keep" "kill" "know" "last" "laugh" "launch" "lay"
      "lead" "lean" "learn" "leave" "let" "lie" "lift" "like" "limit" "link"
      "listen" "live" "look" "lose" "love" "maintain" "make" "manage" "mark"
      "market" "marry" "match" "matter" "mean" "measure" "meet" "mention"
      "mind" "miss" "move" "name" "need" "nod" "note" "notice" "observe"
      "obtain" "occur" "offer" "open" "operate" "order" "organise" "own"
      "paint" "pass" "pay" "perform" "persuade" "pick" "place" "plan" "play"
      "point" "prefer" "prepare" "present" "press" "prevent" "produce"
      "promise" "promote" "propose" "protect" "prove" "provide" "publish"
      "pull" "push" "put" "question" "raise" "reach" "read" "realise" "realize"
      "recall" "receive" "recognise" "recognize" "recommend" "record" "recover"
      "reduce" "refer" "reflect" "refuse" "regard" "reject" "relate" "release"
      "rely" "remain" "remember" "remind" "remove" "repeat" "replace" "reply"
      "report" "represent" "require" "respond" "rest" "result" "retain"
      "return" "reveal" "ride" "ring" "rise" "roll" "run" "satisfy" "save"
      "say" "score" "search" "secure" "see" "seek" "seem" "select" "sell"
      "send" "separate" "serve" "set" "settle" "shake" "share" "shoot" "shout"
      "show" "shut" "sign" "sing" "sit" "sleep" "slip" "smile" "sound" "speak"
      "spend" "spread" "stand" "star" "start" "state" "stay" "steal" "step"
      "stick" "stop" "strike" "study" "succeed" "suffer" "suggest" "supply"
      "support" "suppose" "surround" "survive" "switch" "take" "talk" "teach"
      "tell" "tend" "test" "thank" "think" "threaten" "throw" "touch" "train"
      "transfer" "travel" "treat" "try" "turn" "understand" "undertake" "use"
      "vary" "visit" "vote" "wait" "walk" "want" "warn" "wash" "watch" "wear"
      "welcome" "win" "wish" "withdraw" "wonder" "work" "worry" "write"]})

(def WORDS
  (let [flat-words (apply concat (vals words))]
    (new EnumerationDataType flat-words)))
